"""empty message

Revision ID: 79473aa8c899
Revises: 065db164380c
Create Date: 2019-08-23 21:54:57.041304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79473aa8c899'
down_revision = '065db164380c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
